modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/GCJOJO/BlablaLib/issues"
license = "CC BY-NC-SA 4.0"

[[mods]]
modId = "blablalib"
version = "${version}"
displayName = "BlablaLib"
authors = "GCJOJO"
description = '''
A Simple library for dialogues
'''
logoFile = "assets/blablalib/icon.png"

[[dependencies.blablalib]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blablalib]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blablalib]]
modId = "architectury"
type = "required"
versionRange = "[13.0.11,)"
ordering = "AFTER"
side = "BOTH"

